run:
  timeout: 5m
  tests: true

linters-settings:
  goimports:
    local-prefixes: gitstuff
  
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment

  gosec:
    excludes:
      - G402 # TLS InsecureSkipVerify set true (needed for self-signed certs)

  staticcheck:
    checks: ["all", "-SA1019"] # Ignore deprecated warnings from gitlab library
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: error
      - name: package-comments
        disabled: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - revive
    - ineffassign
    - misspell
    - errcheck
    - gosec
    - unconvert
    - unused
    - staticcheck
  
  disable:
    - typecheck  # handled by go build

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
    
    # Ignore deprecated gitlab library warnings - they're still functional
    - path: internal/gitlab/
      linters: [staticcheck]
      text: "SA1019.*gitlab.*deprecated"