run:
  timeout: 5m
  tests: true

linters-settings:
  goimports:
    local-prefixes: gitstuff
  
  govet:
    check-shadowing: true
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: error
      - name: package-comments
        disabled: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - revive
    - ineffassign
    - misspell
    - errcheck
    - gosec
    - unconvert
    - unused
  
  disable:
    - typecheck  # handled by go build

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec