name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Build cross-platform binaries
        run: |
          # Create dist directory
          mkdir -p dist

          # Get version from tag
          VERSION=${GITHUB_REF#refs/tags/}

          # Build for different platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=$VERSION" -o dist/gitstuff-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.version=$VERSION" -o dist/gitstuff-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=$VERSION" -o dist/gitstuff-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=$VERSION" -o dist/gitstuff-darwin-arm64 .

          # Create checksums
          cd dist
          sha256sum * > checksums.txt
          cd ..

          # Make binaries executable
          chmod +x dist/gitstuff-*


      - name: Generate release notes
        id: release_notes
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          # Create release notes
          cat > release_notes.md << EOF
          # GitStuff $VERSION

          ## Installation

          Choose the appropriate command for your platform:

          **Linux x86_64:**
          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/gitstuff-linux-amd64 -o gitstuff
          chmod +x gitstuff
          sudo mv gitstuff /usr/local/bin/
          \`\`\`

          **Linux ARM64:**
          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/gitstuff-linux-arm64 -o gitstuff
          chmod +x gitstuff
          sudo mv gitstuff /usr/local/bin/
          \`\`\`

          **macOS x86_64:**
          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/gitstuff-darwin-amd64 -o gitstuff
          chmod +x gitstuff
          sudo mv gitstuff /usr/local/bin/
          \`\`\`

          **macOS ARM64 (M1/M2):**
          \`\`\`bash
          curl -L https://github.com/${{ github.repository }}/releases/download/$VERSION/gitstuff-darwin-arm64 -o gitstuff
          chmod +x gitstuff
          sudo mv gitstuff /usr/local/bin/
          \`\`\`

          ## Usage

          After installation, configure your GitLab connection:
          \`\`\`bash
          gitstuff config
          \`\`\`

          Then list your repositories:
          \`\`\`bash
          gitstuff list
          \`\`\`

          See the [README](https://github.com/${{ github.repository }}#usage) for more commands and options.

          ## Verification

          All binaries include checksums for verification. Download [checksums.txt](https://github.com/${{ github.repository }}/releases/download/$VERSION/checksums.txt) and verify with:

          \`\`\`bash
          sha256sum -c checksums.txt
          \`\`\`
          EOF


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: GitStuff ${{ github.ref_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
          files: |
            dist/gitstuff-linux-amd64
            dist/gitstuff-linux-arm64
            dist/gitstuff-darwin-amd64
            dist/gitstuff-darwin-arm64
            dist/checksums.txt
